### PR TITLE
Update to debian buster

### PR DESCRIPTION
**Pull request by jkroepke**

### CODE REVIEW

**Comment by danielshahaf** [comment]
> -- Commit Summary --
> 
>   * Update to debian buster
> 
> -- File Changes --
> 
>     M Dockerfile (11)
>     M README.md (2)

Thanks for the patch, Jan-Otto.  I've cherry-picked the README.md change in c468db6ef7daefb63006bf9e4a5e22a53ce16101, with an appropriate log message.  I'll leave the Dockerfile changes for someone else to review/merge.

**Comment by jkroepke** [comment]
> I'll leave the Dockerfile changes for someone else to review/merge.

Did you found one?

All tests are passend while building the docker image.

I had to switch from `bitnami/minideb-extras:stretch-buildpack` to `bitnami/minideb:buster`, because `bitnami/minideb-extras:stretch-buildpack` was marked as deprecated.

See: https://github.com/bitnami/minideb-extras#deprecation-notice

**Comment by danielshahaf** [comment]
The relevant people are Cc'd to this thread and will chime in when they have time.

**Comment by jkroepke** [comment]
Alright, I saw no CCs. Assignees or Reviewers are empty here, thats why i'm asked.

**Comment by danielshahaf** [comment]
> Alright, I saw no CCs. Assignees or Reviewers are empty here, thats why i'm asked.

I didn't Cc anyone explicitly since I assumed they watch this repository, just like I do.

To be clear, I'm not a hat in this repository; I'm not its "owner", "primary maintainer", "issue manager", or anything of the sort.  I'm just the guy who merges typo fixes :-)

If you don't get a response in a few more days, ping @nicoulaj.  (Or did I just do that for you?  I'm not sure whether comments submitted via email can trigger pings.)

**Comment by jkroepke** [comment]
ping @nicoulaj

**Comment by jkroepke** [comment]
Looks like this is going stale.

**Comment by nicoulaj** [comment]
I can't merge after you deleted your branch, can you please push it again ?

**Pull request merged**
